### ISSUE TITLE
A potential bug in selecting the elite models in MBRL 

### ISSUE THREAD

**Issue by Shentao-YANG** [kzl/lifelong_rl#2]
Hi,

Thanks for providing this wonderful package !

I notice that in line 114 of `lifelong_rl/lifelong_rl/trainers/mbrl/mbrl.py` you have
```
self.ensemble.elites = np.argsort(holdout_losses)
```
AFAIK this line of code will not achieve the goal of selecting the elite models based on the `holdout_losses` since all models will participate in the 'fake' rollouts, as shown in the function `sample` in the base class of model `lifelong_rl/lifelong_rl/models/networks.py/ParallelizedEnsemble`.

Can we adjust this line of code to the following ?
```
self.ensemble.elites = np.argsort(holdout_losses)[:self.num_elites] 
```
I think this will modify the list of `elites` in the base class to include, say, top 5 models out of total 7.

I haven't test this thought yet and please let me know if I miss anything.

Best,
Shentao

**Comment by kzl** [comment]
Thank you for your interest! Unfortunately I no longer am working on this code and have no plans on updating it.

If I recall correctly, the MPC code may have been handling the elites correctly but not the rollout sampling code; however I am not as familiar with the code anymore.
